name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e256247e4a50c17c3f3ddfc0bea6f0f0bcc06e18b758856428d9e1a1a0344683"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
