name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "747e52b8d776d33be490d26f673cc7257919cb2193bfea5ba1997da2a9cd3326"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
