name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04ba8ee0869ebac2d7cd9a58d4459862d2f662a4379217ac2659b01d699faacc"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
