name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "473412ec4251cea2647c384d62cb0485df8d1e61787e476b1e77b778d4283791"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
