name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2193123da859b12106ded127f9c7aa92055cef9eea27ef374f93975780a9925e"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
