name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61c66dd27079f5f5dfd086cbf524646c02d2465ae13797edc17a2f9a0668fa63"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
