name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eb813170fadb06f3da44d92d59b6c24bdacf46ef3e445d6245218748b81dcc7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
