name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde99d51b46c628f248e5951a5198dd226bb58d268688f1248a0642a1699acdc"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
