name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a46c5095fc5f97ac85d1ce7e3e3255c162400f27dcfec7a508aef632f9c8699"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
