name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9eb10875c5e277abfa5e485a3e8086624dafc2ffca66fdb15d4e0b5aa955ebe"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
