name = "Developer's Toolkit"
author = "JosTheDude"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a38204d05df061bfb337f3c96f0bd35294cc461b2bc659fa6976322209d80806"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
